# Generated by Django 5.2 on 2025-06-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='delivery_address',
            field=models.ManyToManyField(blank=True, related_name='delivery_addresses', to='users.addresslist'),
        ),
    ]
