# Generated by Django 5.2 on 2025-06-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_address'),
        ('users', '0004_alter_addresslist_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressList',
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'address')},
        ),
    ]
