# Generated by Django 5.2 on 2025-06-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_address_country_address_nickname'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
    ]
