# Generated by Django 5.2 on 2025-06-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AlterField(
            model_name='address',
            name='nickname',
            field=models.CharField(default='Indirizzo principale', max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
