# Generated by Django 5.2 on 2025-06-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_address_address_alter_address_nickname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
    ]
