# Generated by Django 5.2 on 2025-06-30 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_name'),
        ('users', '0010_remove_address_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_list',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='products.product'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Il numero di telefono deve essere nel formato +CCXXXXXXXXXX o +CCCXXXXXXXXXX (prefisso di 2 o 3 cifre seguito da 10 cifre).', regex='^\\+\\d{2,3}\\d{10}$')]),
        ),
    ]
