# Generated by Django 5.2 on 2025-07-02 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_payment_method_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_cvv',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Il CVV deve essere di 3 cifre numeriche.', regex='^\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_expiry',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='La data di scadenza deve essere nel formato MM/AA.', regex='^\\d{2}/\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Il numero della carta deve essere di 16 cifre numeriche.', regex='^\\d{16}$')]),
        ),
    ]
