# Generated by Django 5.2 on 2025-06-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'permissions': [('view_all_orders', 'Può vedere tutti gli ordini')]},
        ),
    ]
