# Generated by Django 5.2 on 2025-07-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='province',
        ),
    ]
