# Generated by Django 5.2 on 2025-07-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_deliveryaddress_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='credit_card', max_length=50),
        ),
    ]
