# Generated by Django 5.2 on 2025-06-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_deliveryaddress_remove_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='nickname',
            field=models.CharField(default='Indirizzo principale', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
