# Generated by Django 5.2 on 2025-06-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_order_delivered_remove_order_shipped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'In attesa'), ('shipped', 'Spedito'), ('delivered', 'Consegnato'), ('cancelled', 'Annullato')], default='pending', max_length=20),
        ),
    ]
