# Generated by Django 5.2 on 2025-06-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('alimenti', 'Alimenti'), ('abbigliamento', 'Abbigliamento'), ('accessori', 'Accessori'), ('bevande', 'Bevande')], max_length=200, unique=True),
        ),
    ]
